/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Maria
 */
public class Gameplay extends javax.swing.JFrame {
    /**
     * Creates new form gameplay
     */
    public Gameplay() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "Proyecto/src/imagenes/MenuPrincipal3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelTematica, "Proyecto/src/imagenes/8EscalonesCarga.gif");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "Proyecto/src/imagenes/exit.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jTextFieldJugador = new javax.swing.JTextField();
        jButtonRtaA = new javax.swing.JButton();
        jButtonRtaB = new javax.swing.JButton();
        jButtonRtaC = new javax.swing.JButton();
        jButtonRtaD = new javax.swing.JButton();
        jLabelRtaA = new javax.swing.JLabel();
        jLabelRtaB = new javax.swing.JLabel();
        jLabelRtaC = new javax.swing.JLabel();
        jLabelRtaD = new javax.swing.JLabel();
        jTextFieldPregunta = new javax.swing.JTextField();
        jTextFieldTematica = new javax.swing.JTextField();
        jTextFieldEscalon = new javax.swing.JTextField();
        jTextFieldRonda = new javax.swing.JTextField();
        jLabelTematica = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jButtonExit.setBackground(new java.awt.Color(102, 0, 102));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jTextFieldJugador.setEditable(false);
        jTextFieldJugador.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJugador.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldJugador.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJugador.setText("JUGADOR N");
        jTextFieldJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 170, 50));

        jButtonRtaA.setBackground(new java.awt.Color(102, 0, 102));
        jButtonRtaA.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaA.setText("Respuesta");
        jButtonRtaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRtaAActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRtaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 240, 30));

        jButtonRtaB.setBackground(new java.awt.Color(102, 0, 102));
        jButtonRtaB.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaB.setText("Respuesta");
        jPanel1.add(jButtonRtaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 240, 30));

        jButtonRtaC.setBackground(new java.awt.Color(102, 0, 102));
        jButtonRtaC.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaC.setText("Respuesta");
        jPanel1.add(jButtonRtaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 240, 30));

        jButtonRtaD.setBackground(new java.awt.Color(102, 0, 102));
        jButtonRtaD.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaD.setText("Respuesta");
        jButtonRtaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRtaDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRtaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 240, 30));

        jLabelRtaA.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaA.setText("A.");
        jPanel1.add(jLabelRtaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 30, 30));

        jLabelRtaB.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaB.setText("B.");
        jPanel1.add(jLabelRtaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 30, 30));

        jLabelRtaC.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaC.setText("C.");
        jPanel1.add(jLabelRtaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 30, -1));

        jLabelRtaD.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaD.setText("D.");
        jPanel1.add(jLabelRtaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 30, -1));

        jTextFieldPregunta.setEditable(false);
        jTextFieldPregunta.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPregunta.setText("Pregunta");
        jTextFieldPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 580, 70));

        jTextFieldTematica.setEditable(false);
        jTextFieldTematica.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTematica.setText("TEMATICA");
        jTextFieldTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTematicaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 170, 40));

        jTextFieldEscalon.setEditable(false);
        jTextFieldEscalon.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldEscalon.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldEscalon.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEscalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEscalon.setText("ESCALON N");
        jTextFieldEscalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEscalonActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEscalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, -1));

        jTextFieldRonda.setEditable(false);
        jTextFieldRonda.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldRonda.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldRonda.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRonda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRonda.setText("RONDA N");
        jTextFieldRonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRondaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 130, -1));
        jPanel1.add(jLabelTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 580, 350));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonRtaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRtaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRtaDActionPerformed

    private void jTextFieldPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreguntaActionPerformed

    private void jTextFieldJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJugadorActionPerformed

    private void jButtonRtaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRtaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRtaAActionPerformed

    private void jTextFieldTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTematicaActionPerformed

    private void jTextFieldEscalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEscalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEscalonActionPerformed

    private void jTextFieldRondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRondaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRondaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gameplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonExit;
    public javax.swing.JButton jButtonRtaA;
    public javax.swing.JButton jButtonRtaB;
    public javax.swing.JButton jButtonRtaC;
    public javax.swing.JButton jButtonRtaD;
    public javax.swing.JLabel jLabelExit;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelRtaA;
    public javax.swing.JLabel jLabelRtaB;
    public javax.swing.JLabel jLabelRtaC;
    public javax.swing.JLabel jLabelRtaD;
    public javax.swing.JLabel jLabelTematica;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldEscalon;
    public javax.swing.JTextField jTextFieldJugador;
    public javax.swing.JTextField jTextFieldPregunta;
    public javax.swing.JTextField jTextFieldRonda;
    public javax.swing.JTextField jTextFieldTematica;
    
    public javax.swing.JButton getjButtonExit() {
        return jButtonExit;
    }

    public javax.swing.JButton getjButtonRtaA() {
        return jButtonRtaA;
    }

    public javax.swing.JButton getjButtonRtaB() {
        return jButtonRtaB;
    }

    public javax.swing.JButton getjButtonRtaC() {
        return jButtonRtaC;
    }

    public javax.swing.JButton getjButtonRtaD() {
        return jButtonRtaD;
    }

    public javax.swing.JTextField getjTextFieldEscalon() {
        return jTextFieldEscalon;
    }

    public javax.swing.JTextField getjTextFieldJugador() {
        return jTextFieldJugador;
    }

    public javax.swing.JTextField getjTextFieldPregunta() {
        return jTextFieldPregunta;
    }

    public javax.swing.JTextField getjTextFieldRonda() {
        return jTextFieldRonda;
    }

    public javax.swing.JTextField getjTextFieldTematica() {
        return jTextFieldTematica;
    }
    // End of variables declaration//GEN-END:variables
}

