/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.Timer; 
import java.awt.event.ActionEvent; 
import java.awt.event.ActionListener; 
import javax.swing.JOptionPane;

/**
 *
 * @author Maria
 */
public class Gameplay extends javax.swing.JFrame {
    private Timer timer; 
    private int tiempo;
    /**
     * Creates new form gameplay
     */
    public Gameplay() {
        initComponents();
        iniciarCronometro();
        RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/azul.png");
        RSScaleLabel.setScaleLabel(jLabelTematica, "src/imagenes/historia.png");
        RSScaleLabel.setScaleLabel(jLabelIconUser, "src/imagenes/user.png");
        RSScaleLabel.setScaleLabel(jLabelExit, "src/imagenes/exit.png");
        RSScaleLabel.setScaleLabel(jLabelConfig, "src/imagenes/config.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelConfig, "src/imagenes/config.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelConfig = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonConfig = new javax.swing.JButton();
        jLabelIconUser = new javax.swing.JLabel();
        jLabelJugador = new javax.swing.JLabel();
        jTextFieldJugador = new javax.swing.JTextField();
        jButtonRtaA = new javax.swing.JButton();
        jButtonRtaB = new javax.swing.JButton();
        jButtonRtaC = new javax.swing.JButton();
        jButtonRtaD = new javax.swing.JButton();
        jLabelRonda = new javax.swing.JLabel();
        jLabelTurnoDe = new javax.swing.JLabel();
        jLabelEscalon = new javax.swing.JLabel();
        jLabelRtaA = new javax.swing.JLabel();
        jLabelRtaB = new javax.swing.JLabel();
        jLabelRtaC = new javax.swing.JLabel();
        jLabelRtaD = new javax.swing.JLabel();
        jTextFieldPregunta = new javax.swing.JTextField();
        jLabelTiempo = new javax.swing.JLabel();
        jProgressBarTiempo = new javax.swing.JProgressBar();
        jLabelTematica = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));
        jPanel1.add(jLabelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 30, 20));

        jButtonExit.setBackground(new java.awt.Color(0, 0, 153));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jButtonConfig.setBackground(new java.awt.Color(0, 0, 153));
        jButtonConfig.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonConfig.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 40));
        jPanel1.add(jLabelIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 40, 30));

        jLabelJugador.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabelJugador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJugador.setText("Jugador N");
        jPanel1.add(jLabelJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, 30));

        jTextFieldJugador.setEditable(false);
        jTextFieldJugador.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJugador.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJugador.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 170, 50));

        jButtonRtaA.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRtaA.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaA.setText("Respuesta");
        jPanel1.add(jButtonRtaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 240, 30));

        jButtonRtaB.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRtaB.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaB.setText("Respuesta");
        jPanel1.add(jButtonRtaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 240, 30));

        jButtonRtaC.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRtaC.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaC.setText("Respuesta");
        jPanel1.add(jButtonRtaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 240, 30));

        jButtonRtaD.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRtaD.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRtaD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaD.setText("Respuesta");
        jButtonRtaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRtaDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRtaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 240, 30));

        jLabelRonda.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        jLabelRonda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRonda.setText("(1/2)");
        jPanel1.add(jLabelRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 30));

        jLabelTurnoDe.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        jLabelTurnoDe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTurnoDe.setText("Turno de");
        jPanel1.add(jLabelTurnoDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, 50));

        jLabelEscalon.setFont(new java.awt.Font("Roboto Medium", 3, 30)); // NOI18N
        jLabelEscalon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEscalon.setText("ESCALON N");
        jPanel1.add(jLabelEscalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, 60));

        jLabelRtaA.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaA.setText("A.");
        jPanel1.add(jLabelRtaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 30, 30));

        jLabelRtaB.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaB.setText("B.");
        jPanel1.add(jLabelRtaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 30, 30));

        jLabelRtaC.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaC.setText("C.");
        jPanel1.add(jLabelRtaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 30, -1));

        jLabelRtaD.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaD.setText("D.");
        jPanel1.add(jLabelRtaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 30, -1));

        jTextFieldPregunta.setEditable(false);
        jTextFieldPregunta.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPregunta.setText("Pregunta");
        jTextFieldPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 580, 70));

        jLabelTiempo.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabelTiempo.setText("30");
        jPanel1.add(jLabelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jProgressBarTiempo.setForeground(new java.awt.Color(0, 0, 153));
        jProgressBarTiempo.setMaximum(30);
        jProgressBarTiempo.setValue(30);
        jPanel1.add(jProgressBarTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 580, 20));
        jPanel1.add(jLabelTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 580, 300));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -390, 660, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonRtaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRtaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRtaDActionPerformed

    private void jTextFieldPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreguntaActionPerformed

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfigActionPerformed

    private void jTextFieldJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gameplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRtaA;
    private javax.swing.JButton jButtonRtaB;
    private javax.swing.JButton jButtonRtaC;
    private javax.swing.JButton jButtonRtaD;
    private javax.swing.JLabel jLabelConfig;
    private javax.swing.JLabel jLabelEscalon;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIconUser;
    private javax.swing.JLabel jLabelJugador;
    private javax.swing.JLabel jLabelRonda;
    private javax.swing.JLabel jLabelRtaA;
    private javax.swing.JLabel jLabelRtaB;
    private javax.swing.JLabel jLabelRtaC;
    private javax.swing.JLabel jLabelRtaD;
    private javax.swing.JLabel jLabelTematica;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JLabel jLabelTurnoDe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBarTiempo;
    private javax.swing.JTextField jTextFieldJugador;
    private javax.swing.JTextField jTextFieldPregunta;
    // End of variables declaration//GEN-END:variables
    private void iniciarCronometro(){
    tiempo=30;
    timer = new Timer(1000, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) { 
            tiempo--;
            jLabelTiempo.setText(String.valueOf(tiempo)); 
            jProgressBarTiempo.setValue(tiempo); 
            if (tiempo <= 0) { 
                timer.stop();
                JOptionPane.showMessageDialog(null, "¡Se acabó el tiempo!"); 
            }
        }
    });
    timer.start();
    }
}

