/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ventanas;

/**
 *
 * @author Maria
 */
public class MenuPruebas extends javax.swing.JFrame {   
    /**
     * Creates new form gameplay
     */
    public MenuPruebas() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/azul.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonModoAdmin = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonJugar1 = new javax.swing.JButton();
        jButtonOpciones = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Roboto Medium", 0, 50)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("8 ESCALONES");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 330, 70));

        jButtonModoAdmin.setBackground(new java.awt.Color(0, 0, 153));
        jButtonModoAdmin.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonModoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModoAdmin.setText("MODO ADMIN");
        jButtonModoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoAdminActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 260, 50));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 153));
        jButtonSalir.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 260, 50));

        jButtonJugar1.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJugar1.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJugar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJugar1.setText("JUGAR");
        jButtonJugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 260, 50));

        jButtonOpciones.setBackground(new java.awt.Color(0, 0, 153));
        jButtonOpciones.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonOpciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOpciones.setText("OPCIONES");
        jButtonOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcionesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 260, 50));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -390, 660, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonModoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoAdminActionPerformed
        ModoAdmin newFrame = new ModoAdmin();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonModoAdminActionPerformed

    private void jButtonJugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugar1ActionPerformed
        Perfiles newFrame = new Perfiles();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJugar1ActionPerformed

    private void jButtonOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcionesActionPerformed
        Opciones newFrame = new Opciones();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonJugar1;
    public javax.swing.JButton jButtonModoAdmin;
    public javax.swing.JButton jButtonOpciones;
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

