/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.ActionListener;

import controlador.ControladorABMPreguntas;

/**
 *
 * @author Maria
 */
public class ABMPreguntas extends javax.swing.JFrame {   
    /**
     * Creates new form gameplay
     */
    public ABMPreguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "Proyecto/src/imagenes/codigo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconAdmin, "Proyecto/src/imagenes/admin.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconEdit, "Proyecto/src/imagenes/lapiz.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconDelete, "Proyecto/src/imagenes/basura.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoTematica, "Proyecto/src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoTipo, "Proyecto/src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoPregunta, "Proyecto/src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelBack, "Proyecto/src/imagenes/back.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "Proyecto/src/imagenes/exit.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIconAdmin = new javax.swing.JLabel();
        jTextFieldABMPreguntas = new javax.swing.JTextField();
        jTextFieldTematica = new javax.swing.JTextField();
        jComboBoxTematica = new javax.swing.JComboBox<>();
        jTextFieldTipo = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxPregunta = new javax.swing.JComboBox<>();
        jTextFieldNuevaPregunta = new javax.swing.JTextField();
        jLabelBack = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelIconEdit = new javax.swing.JLabel();
        jLabelIconDelete = new javax.swing.JLabel();
        jButtonEliminarPregunta = new javax.swing.JButton();
        jButtonModificarPregunta = new javax.swing.JButton();
        jButtonAgregarPregunta = new javax.swing.JButton();
        jLabelFondoTematica = new javax.swing.JLabel();
        jLabelFondoTipo = new javax.swing.JLabel();
        jLabelFondoPregunta = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 110, 100));

        jTextFieldABMPreguntas.setEditable(false);
        jTextFieldABMPreguntas.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldABMPreguntas.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jTextFieldABMPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldABMPreguntas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldABMPreguntas.setText("PREGUNTAS");
        jPanel1.add(jTextFieldABMPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 300, 70));

        jTextFieldTematica.setEditable(false);
        jTextFieldTematica.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTematica.setText("Tematica");
        jPanel1.add(jTextFieldTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 60));

        jComboBoxTematica.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxTematica.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("tematica presionado");
            }
        });
        jPanel1.add(jComboBoxTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 160, 60));

        jTextFieldTipo.setEditable(false);
        jTextFieldTipo.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTipo.setText("Tipo");
        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 80, 60));

        jComboBoxTipo.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multiple choice", "Aproximacion"}));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("tipo presionado");
            }
        });
        jPanel1.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 160, 60));

        jComboBoxPregunta.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 570, 50));

        jTextFieldNuevaPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jTextFieldNuevaPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldNuevaPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNuevaPregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFieldNuevaPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 570, 50));
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 30));
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 40, 30));

        jButtonExit.setBackground(new java.awt.Color(0, 102, 0));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 60, 50));

        jButtonBack.setBackground(new java.awt.Color(0, 102, 0));
        jButtonBack.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));
        jPanel1.add(jLabelIconEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, 50));
        jPanel1.add(jLabelIconDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 60, 50));

        jButtonEliminarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEliminarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonEliminarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 80, 70));

        jButtonModificarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonModificarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonModificarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 80, 70));

        jButtonAgregarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAgregarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 70)); // NOI18N
        jButtonAgregarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarPregunta.setText("+");
        jButtonAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 80, 70));
        jPanel1.add(jLabelFondoTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 290, 80));
        jPanel1.add(jLabelFondoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 270, 80));
        jPanel1.add(jLabelFondoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 590, 130));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonEliminarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarPreguntaActionPerformed

    private void jButtonModificarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarPreguntaActionPerformed

    private void jButtonAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPreguntaActionPerformed

    private void jComboBoxPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPreguntaActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed
    public void listenerTematica(ActionListener listener) {
        jComboBoxTematica.addActionListener(listener);
    }
    public void listenerTipo(ActionListener listener) {
        jComboBoxTipo.addActionListener(listener);
    }
    public void listenerInsertar(ActionListener listener) {
        jButtonAgregarPregunta.addActionListener(listener);
    }
    public void listenerEliminar(ActionListener listener) {
        jButtonEliminarPregunta.addActionListener(listener);
    }
    public void listenerActualizar(ActionListener listener) {
        jButtonModificarPregunta.addActionListener(listener);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  ControladorABMPreguntas c = new ControladorABMPreguntas();
                new ABMPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarPregunta;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEliminarPregunta;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonModificarPregunta;
    private javax.swing.JComboBox<String> jComboBoxPregunta;
    private javax.swing.JComboBox<String> jComboBoxTematica;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoPregunta;
    private javax.swing.JLabel jLabelFondoTematica;
    private javax.swing.JLabel jLabelFondoTipo;
    private javax.swing.JLabel jLabelIconAdmin;
    private javax.swing.JLabel jLabelIconDelete;
    private javax.swing.JLabel jLabelIconEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldABMPreguntas;
    private javax.swing.JTextField jTextFieldNuevaPregunta;
    private javax.swing.JTextField jTextFieldTematica;
    private javax.swing.JTextField jTextFieldTipo;
    public javax.swing.JButton getjButtonAgregarPregunta() {
        return jButtonAgregarPregunta;
    }

    public javax.swing.JButton getjButtonEliminarPregunta() {
        return jButtonEliminarPregunta;
    }

    public javax.swing.JButton getjButtonModificarPregunta() {
        return jButtonModificarPregunta;
    }

    // End of variables declaration//GEN-END:variables
    public javax.swing.JComboBox<String> getjComboBoxPregunta() {
        return jComboBoxPregunta;
    }

    public javax.swing.JComboBox<String> getjComboBoxTematica() {
        return jComboBoxTematica;
    }

    public javax.swing.JComboBox<String> getjComboBoxTipo() {
        return jComboBoxTipo;
    }

    public javax.swing.JTextField getjTextFieldNuevaPregunta() {
        return jTextFieldNuevaPregunta;
    }
}

