/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.event.ActionListener;
/**
 *
 * @author Maria
 */
public class ABMPreguntas extends javax.swing.JFrame {   
    /**
     * Creates new form gameplay
     */
    public ABMPreguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "Proyecto/src/imagenes/codigo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconAdmin, "Proyecto/src/imagenes/admin.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconEdit, "Proyecto/src/imagenes/lapiz.png");
      //  rsscalelabel.RSScaleLabel.setScaleLabel(jLabelSave, "Proyecto/src/imagenes/guardar.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconDelete, "Proyecto/src/imagenes/basura.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoTematica, "Proyecto/src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoTipo, "Proyecto/src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoPregunta, "Proyecto/src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelBack, "Proyecto/src/imagenes/back.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIconAdmin = new javax.swing.JLabel();
        jTextFieldPreguntas = new javax.swing.JTextField();
        jTextFieldTematica = new javax.swing.JTextField();
        jComboBoxTematica = new javax.swing.JComboBox<>();
        jTextFieldTipo = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxPregunta = new javax.swing.JComboBox<>();
        jLabelBack = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelIconEdit = new javax.swing.JLabel();
        jLabelIconDelete = new javax.swing.JLabel();
        jLabelSave = new javax.swing.JLabel();
        // jButtonSave = new javax.swing.JButton();
        jButtonEliminarPregunta = new javax.swing.JButton();
        jButtonEditarPregunta = new javax.swing.JButton();
        jButtonAgregarPregunta = new javax.swing.JButton();
        jLabelFondoTematica = new javax.swing.JLabel();
        jLabelFondoTipo = new javax.swing.JLabel();
        jLabelFondoPregunta = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 110, 100));

        jTextFieldPreguntas.setEditable(false);
        jTextFieldPreguntas.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldPreguntas.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jTextFieldPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPreguntas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPreguntas.setText("PREGUNTAS");
        jPanel1.add(jTextFieldPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 230, 70));

        jTextFieldTematica.setEditable(false);
        jTextFieldTematica.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTematica.setText("Tematica");
        jPanel1.add(jTextFieldTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, 60));

        jComboBoxTematica.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxTematica.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jComboBoxTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, 60));

        jTextFieldTipo.setEditable(false);
        jTextFieldTipo.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTipo.setText("Tipo");
        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 80, 60));

        jComboBoxTipo.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multiple choice", "Aproximacion"}));
        jPanel1.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 160, 60));

        jComboBoxPregunta.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 570, 50));
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 30));

        jButtonBack.setBackground(new java.awt.Color(0, 102, 0));
        jButtonBack.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));
        jPanel1.add(jLabelIconEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 60, 50));
        jPanel1.add(jLabelIconDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 60, 50));
        jPanel1.add(jLabelSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 60, 50));

        // jButtonSave.setBackground(new java.awt.Color(0, 102, 0));
        // jButtonSave.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        // jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        // jButtonSave.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         jButtonSaveActionPerformed(evt);
        //     }
        // });
        // jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 80, 70));

        jButtonEliminarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEliminarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonEliminarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 80, 70));

        jButtonEditarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEditarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonEditarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 80, 70));

        jButtonAgregarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAgregarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 70)); // NOI18N
        jButtonAgregarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarPregunta.setText("+");
        jButtonAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 80, 70));
        jPanel1.add(jLabelFondoTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 290, 80));
        jPanel1.add(jLabelFondoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 270, 80));
        jPanel1.add(jLabelFondoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 590, 70));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonEliminarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarPreguntaActionPerformed

    private void jButtonEditarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarPreguntaActionPerformed

    private void jButtonAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPreguntaActionPerformed

    private void jComboBoxPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPreguntaActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAgregarPregunta;
    public javax.swing.JButton jButtonBack;
    public javax.swing.JButton jButtonEditarPregunta;
    public javax.swing.JButton jButtonEliminarPregunta;
   // public javax.swing.JButton jButtonSave;
    public javax.swing.JComboBox<String> jComboBoxPregunta;
    public javax.swing.JComboBox<String> jComboBoxTematica;
    public javax.swing.JComboBox<String> jComboBoxTipo;
    public javax.swing.JLabel jLabelBack;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelFondoPregunta;
    public javax.swing.JLabel jLabelFondoTematica;
    public javax.swing.JLabel jLabelFondoTipo;
    public javax.swing.JLabel jLabelIconAdmin;
    public javax.swing.JLabel jLabelIconDelete;
    public javax.swing.JLabel jLabelIconEdit;
    public javax.swing.JLabel jLabelSave;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldPreguntas;
    public javax.swing.JTextField jTextFieldTematica;
    public javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjButtonBack() {
        return jButtonBack;
    }
    
    // public javax.swing.JButton getjButtonSave() {
    //     return jButtonSave;
    // }
    
    public javax.swing.JButton getjButtonEliminarPregunta() {
        return jButtonEliminarPregunta;
    }
    
    public javax.swing.JButton getjButtonEditarPregunta() {
        return jButtonEditarPregunta;
    }
    
    public javax.swing.JButton getjTextFieldNuevaPregunta() {
        return jButtonAgregarPregunta;
    }
    public javax.swing.JComboBox<String> getjComboBoxPregunta() {
        return jComboBoxPregunta;
    }
    
    public javax.swing.JComboBox<String> getjComboBoxTematica() {
        return jComboBoxTematica;
    }
    
    public javax.swing.JComboBox<String> getjComboBoxTipo() {
        return jComboBoxTipo;
    }

    public void listenerTematica(ActionListener listener) {
        jComboBoxTematica.addActionListener(listener);
    }
    public void listenerTipo(ActionListener listener) {
        jComboBoxTipo.addActionListener(listener);
    }
    public void listenerInsertar(ActionListener listener) {
        jButtonAgregarPregunta.addActionListener(listener);
    }
    public void listenerEliminar(ActionListener listener) {
        jButtonEliminarPregunta.addActionListener(listener);
    }
    public void listenerActualizar(ActionListener listener) {
        jButtonEditarPregunta.addActionListener(listener);
    }
}

