/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Maria
 */
public class GameplayAproximacion extends javax.swing.JFrame {
    /**
     * Creates new form gameplay
     */
    public GameplayAproximacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/MenuPrincipal3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelTematica, "src/imagenes/historia.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "src/imagenes/exit.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jTextFieldJugador = new javax.swing.JTextField();
        jTextFieldPregunta = new javax.swing.JTextField();
        jLabelTematica = new javax.swing.JLabel();
        jTextFieldRespuestaAprox = new javax.swing.JTextField();
        jTextFieldTematica = new javax.swing.JTextField();
        Respuesta = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jButtonExit.setBackground(new java.awt.Color(102, 0, 102));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jTextFieldJugador.setEditable(false);
        jTextFieldJugador.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJugador.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldJugador.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJugador.setText("JUGADOR N");
        jTextFieldJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, 50));

        jTextFieldPregunta.setEditable(false);
        jTextFieldPregunta.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPregunta.setText("Pregunta");
        jTextFieldPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 580, 70));
        jPanel1.add(jLabelTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, 300));

        jTextFieldRespuestaAprox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuestaAproxActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRespuestaAprox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 380, 40));

        jTextFieldTematica.setEditable(false);
        jTextFieldTematica.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTematica.setText("TEMATICA");
        jTextFieldTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTematicaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 40));

        Respuesta.setBackground(new java.awt.Color(102, 0, 102));
        Respuesta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        Respuesta.setForeground(new java.awt.Color(255, 255, 255));
        Respuesta.setText("Respuesta");
        Respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("Botón respuesta presionado");
            }
        });
        jPanel1.add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 190, 40));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -390, 650, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void listenerRta(ActionListener listener) {
        Respuesta.addActionListener(listener);
    }

    private void jTextFieldTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTematicaActionPerformed

    private void jTextFieldRespuestaAproxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuestaAproxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespuestaAproxActionPerformed

    private void jTextFieldPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreguntaActionPerformed

    private void jTextFieldJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJugadorActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed

    }//GEN-LAST:event_jButtonExitActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameplayAproximacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameplayAproximacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameplayAproximacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameplayAproximacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameplayAproximacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Respuesta;
    public javax.swing.JButton jButtonExit;
    public javax.swing.JLabel jLabelExit;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelTematica;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldJugador;
    public javax.swing.JTextField jTextFieldPregunta;
    public javax.swing.JTextField jTextFieldRespuestaAprox;
    public javax.swing.JTextField jTextFieldTematica;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getjTextFieldPregunta() {
        return jTextFieldPregunta;
    }

    public javax.swing.JTextField getTematica() {
        return jTextFieldTematica;
    }

    public javax.swing.JButton getResultadoAprox() {
        return Respuesta;
    }
}

