
package Vista;
import controlador.*;

/**
 *
 * @author Maria
 */
public class ModoAdmin extends javax.swing.JFrame {   
    /**
     * Creates new form gameplay
     */
    public ModoAdmin() {
        setLookandFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/codigo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelBack, "src/imagenes/back.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconAdmin, "src/imagenes/admin.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jButtonABMPreguntas = new javax.swing.JButton(); //Cierra y abre vistaABMPreguntas
        jButtonABMTematicas = new javax.swing.JButton(); //Cierra y abre vistaABMPTematicas
        jLabelBack = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonABMJugadores = new javax.swing.JButton();
        jLabelIconAdmin = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("MODO");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, 40));

        jLabelTitulo1.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setText("ADMIN");
        jPanel1.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 40));

        jButtonABMPreguntas.setBackground(new java.awt.Color(51, 153, 0));
        jButtonABMPreguntas.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jButtonABMPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonABMPreguntas.setText("ABM Preguntas");
        /*jButtonABMPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonABMPreguntasActionPerformed(evt);
            }
        });*/
        jPanel1.add(jButtonABMPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 260, 50));

        jButtonABMTematicas.setBackground(new java.awt.Color(51, 153, 0));
        jButtonABMTematicas.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jButtonABMTematicas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonABMTematicas.setText("ABM Tematicas");
        /*jButtonABMTematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonABMTematicasActionPerformed(evt);
            }
        });*/
        jPanel1.add(jButtonABMTematicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 260, 50));
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jButtonBack.setBackground(new java.awt.Color(51, 153, 0));
        jButtonBack.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        /*jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });*/
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jButtonABMJugadores.setBackground(new java.awt.Color(51, 153, 0));
        jButtonABMJugadores.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jButtonABMJugadores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonABMJugadores.setText("ABM Jugadores");
        /*jButtonABMJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonABMJugadoresActionPerformed(evt);
            }
        });*/
        jPanel1.add(jButtonABMJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 260, 50));
        jPanel1.add(jLabelIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 100));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    /*private void jButtonABMPreguntasActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jButtonABMTematicasActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jButtonABMJugadoresActionPerformed(java.awt.event.ActionEvent evt) {}*/

    /**
     * @param args the command line arguments
     */

    private void setLookandFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    /*public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonABMJugadores;
    private javax.swing.JButton jButtonABMPreguntas;
    private javax.swing.JButton jButtonABMTematicas;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIconAdmin;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    //Getters botones
    public javax.swing.JButton getjButtonABMJugadores() {
        return jButtonABMJugadores;
    }

    public javax.swing.JButton getjButtonABMPreguntas() {
        return jButtonABMPreguntas;
    }

    public javax.swing.JButton getjButtonABMTematicas() {
        return jButtonABMTematicas;
    }

    public javax.swing.JButton getjButtonBack() {
        return jButtonBack;
    }
}

