/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.ControladorSeleccionarJugadores;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.*; 
import java.awt.*;

/**
 *
 * @author Maria
 */
public class SeleccionarJugador extends javax.swing.JFrame {

    /**
     * Creates new form gameplay
     */
    public SeleccionarJugador() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/MenuPrincipal3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo2, "src/imagenes/violeta.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "src/imagenes/exit.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelBack, "src/imagenes/back.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelJugar, "src/imagenes/derecha.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser1, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser2, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser3, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser4, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser5, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser6, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser7, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser8, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser9, "src/imagenes/user.png");
        new ControladorSeleccionarJugadores(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelJugar = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonJugar = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelUser1 = new javax.swing.JLabel();
        jLabelUser2 = new javax.swing.JLabel();
        jLabelUser3 = new javax.swing.JLabel();
        jLabelUser4 = new javax.swing.JLabel();
        jLabelUser5 = new javax.swing.JLabel();
        jLabelUser6 = new javax.swing.JLabel();
        jLabelUser7 = new javax.swing.JLabel();
        jLabelUser8 = new javax.swing.JLabel();
        jLabelUser9 = new javax.swing.JLabel();
        jButtonJ1 = new javax.swing.JButton();
        jButtonJ2 = new javax.swing.JButton();
        jButtonJ3 = new javax.swing.JButton();
        jButtonJ4 = new javax.swing.JButton();
        jButtonJ5 = new javax.swing.JButton();
        jButtonJ6 = new javax.swing.JButton();
        jButtonJ7 = new javax.swing.JButton();
        jButtonJ8 = new javax.swing.JButton();
        jButtonJ9 = new javax.swing.JButton();
        jTextFieldSeleccionarJugador = new javax.swing.JTextField();
        jComboBoxJ1 = new javax.swing.JComboBox<>();
        jComboBoxJ2 = new javax.swing.JComboBox<>();
        jComboBoxJ3 = new javax.swing.JComboBox<>();
        jComboBoxJ4 = new javax.swing.JComboBox<>();
        jComboBoxJ5 = new javax.swing.JComboBox<>();
        jComboBoxJ6 = new javax.swing.JComboBox<>();
        jComboBoxJ7 = new javax.swing.JComboBox<>();
        jComboBoxJ8 = new javax.swing.JComboBox<>();
        jComboBoxJ9 = new javax.swing.JComboBox<>();
        jLabelFondo2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 30, 20));
        jPanel1.add(jLabelJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 30, 20));
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jButtonExit.setBackground(new java.awt.Color(102, 0, 102));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 40));

        jButtonJugar.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJugar.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonJugar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 40));

        jButtonBack.setBackground(new java.awt.Color(102, 0, 102));
        jButtonBack.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));
        jPanel1.add(jLabelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 100));
        jPanel1.add(jLabelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 100, 100));
        jPanel1.add(jLabelUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 100, 100));
        jPanel1.add(jLabelUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 100, 100));
        jPanel1.add(jLabelUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 100, 100));
        jPanel1.add(jLabelUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, 100));
        jPanel1.add(jLabelUser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 100, 100));
        jPanel1.add(jLabelUser8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 100, 100));
        jPanel1.add(jLabelUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 100, 100));

        jButtonJ1.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ1.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jButtonJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 120));

        jButtonJ2.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ2.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 120, 120));

        jButtonJ3.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ3.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 120, 120));

        jButtonJ4.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ4.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 120, 120));

        jButtonJ5.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ5.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 120, 120));

        jButtonJ6.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ6.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, 120));

        jButtonJ7.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ7.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 120, 120));

        jButtonJ8.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ8.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 120, 120));

        jButtonJ9.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ9.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 120, 120));

        jTextFieldSeleccionarJugador.setEditable(false);
        jTextFieldSeleccionarJugador.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldSeleccionarJugador.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldSeleccionarJugador.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSeleccionarJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSeleccionarJugador.setText("SELECCIONAR JUGADORES");
        jTextFieldSeleccionarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeleccionarJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSeleccionarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 270, 40));

        jComboBoxJ1.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ1.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jPanel1.add(jComboBoxJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, -1));

        jComboBoxJ2.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ2.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 120, -1));

        jComboBoxJ3.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ3.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 120, -1));

        jComboBoxJ4.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ4.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, -1));

        jComboBoxJ5.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ5.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 120, -1));

        jComboBoxJ6.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ6.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ6.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 120, -1));

        jComboBoxJ7.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ7.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ7.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ7ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 120, -1));

        jComboBoxJ8.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ8.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ8.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ8ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 120, -1));

        jComboBoxJ9.setBackground(new java.awt.Color(102, 0, 102));
        jComboBoxJ9.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxJ9.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxJ9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxJ9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJ9ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 120, -1));
        jPanel1.add(jLabelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 520));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ4ActionPerformed
    }//GEN-LAST:event_jButtonJ4ActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ2ActionPerformed
    }//GEN-LAST:event_jButtonJ2ActionPerformed

    private void jButtonJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ1ActionPerformed
    }//GEN-LAST:event_jButtonJ1ActionPerformed

    private void jButtonJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ5ActionPerformed
    }//GEN-LAST:event_jButtonJ5ActionPerformed

    private void jButtonJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ7ActionPerformed
    }//GEN-LAST:event_jButtonJ7ActionPerformed

    private void jButtonJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ8ActionPerformed
    }//GEN-LAST:event_jButtonJ8ActionPerformed

    private void jButtonJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ3ActionPerformed
    }//GEN-LAST:event_jButtonJ3ActionPerformed

    private void jButtonJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ6ActionPerformed
    }//GEN-LAST:event_jButtonJ6ActionPerformed

    private void jButtonJ9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ9ActionPerformed
    }//GEN-LAST:event_jButtonJ9ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldSeleccionarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeleccionarJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSeleccionarJugadorActionPerformed

    private void jComboBoxJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ1ActionPerformed

    private void jComboBoxJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ2ActionPerformed

    private void jComboBoxJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ3ActionPerformed

    private void jComboBoxJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ4ActionPerformed

    private void jComboBoxJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ5ActionPerformed

    private void jComboBoxJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ6ActionPerformed

    private void jComboBoxJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ7ActionPerformed

    private void jComboBoxJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ8ActionPerformed

    private void jComboBoxJ9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJ9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJ9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBack;
    public javax.swing.JButton jButtonExit;
    public javax.swing.JButton jButtonJ1;
    public javax.swing.JButton jButtonJ2;
    public javax.swing.JButton jButtonJ3;
    public javax.swing.JButton jButtonJ4;
    public javax.swing.JButton jButtonJ5;
    public javax.swing.JButton jButtonJ6;
    public javax.swing.JButton jButtonJ7;
    public javax.swing.JButton jButtonJ8;
    public javax.swing.JButton jButtonJ9;
    public javax.swing.JButton jButtonJugar;
    public javax.swing.JComboBox<String> jComboBoxJ1;
    public javax.swing.JComboBox<String> jComboBoxJ2;
    public javax.swing.JComboBox<String> jComboBoxJ3;
    public javax.swing.JComboBox<String> jComboBoxJ4;
    public javax.swing.JComboBox<String> jComboBoxJ5;
    public javax.swing.JComboBox<String> jComboBoxJ6;
    public javax.swing.JComboBox<String> jComboBoxJ7;
    public javax.swing.JComboBox<String> jComboBoxJ8;
    public javax.swing.JComboBox<String> jComboBoxJ9;
    public javax.swing.JLabel jLabelBack;
    public javax.swing.JLabel jLabelExit;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelFondo2;
    public javax.swing.JLabel jLabelJugar;
    public javax.swing.JLabel jLabelUser1;
    public javax.swing.JLabel jLabelUser2;
    public javax.swing.JLabel jLabelUser3;
    public javax.swing.JLabel jLabelUser4;
    public javax.swing.JLabel jLabelUser5;
    public javax.swing.JLabel jLabelUser6;
    public javax.swing.JLabel jLabelUser7;
    public javax.swing.JLabel jLabelUser8;
    public javax.swing.JLabel jLabelUser9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldSeleccionarJugador;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<String> getComboBoxJ1() {
        return jComboBoxJ1;
    }
}
