/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Maria
 */
public class SeleccionarIconPerfil extends javax.swing.JFrame {

    /**
     * Creates new form gameplay
     */
    public SeleccionarIconPerfil() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "Proyecto/src/imagenes/MenuPrincipal3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo2, "Proyecto/src/imagenes/violeta.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "Proyecto/src/imagenes/exit.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelBack, "Proyecto/src/imagenes/back.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser1, "Proyecto/src/imagenes/IconUser1.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser2, "Proyecto/src/imagenes/IconUser2.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser3, "Proyecto/src/imagenes/IconUser3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser4, "Proyecto/src/imagenes/IconUser4.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser5, "Proyecto/src/imagenes/IconUser5.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser6, "Proyecto/src/imagenes/IconUser6.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser7, "Proyecto/src/imagenes/IconUser7.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser8, "Proyecto/src/imagenes/IconUser8.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser9, "Proyecto/src/imagenes/IconUser9.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser10, "Proyecto/src/imagenes/IconUser10.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser11, "Proyecto/src/imagenes/IconUser11.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser12, "Proyecto/src/imagenes/IconUser12.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser13, "Proyecto/src/imagenes/IconUser13.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser14, "Proyecto/src/imagenes/IconUser14.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser15, "Proyecto/src/imagenes/IconUser15.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser16, "Proyecto/src/imagenes/IconUser16.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelUser1 = new javax.swing.JLabel();
        jLabelUser2 = new javax.swing.JLabel();
        jLabelUser3 = new javax.swing.JLabel();
        jLabelUser4 = new javax.swing.JLabel();
        jLabelUser5 = new javax.swing.JLabel();
        jLabelUser6 = new javax.swing.JLabel();
        jLabelUser7 = new javax.swing.JLabel();
        jLabelUser8 = new javax.swing.JLabel();
        jLabelUser9 = new javax.swing.JLabel();
        jLabelUser10 = new javax.swing.JLabel();
        jLabelUser11 = new javax.swing.JLabel();
        jLabelUser12 = new javax.swing.JLabel();
        jLabelUser13 = new javax.swing.JLabel();
        jLabelUser14 = new javax.swing.JLabel();
        jLabelUser15 = new javax.swing.JLabel();
        jLabelUser16 = new javax.swing.JLabel();
        jButtonJ1 = new javax.swing.JButton();
        jButtonJ2 = new javax.swing.JButton();
        jButtonJ3 = new javax.swing.JButton();
        jButtonJ4 = new javax.swing.JButton();
        jButtonJ5 = new javax.swing.JButton();
        jButtonJ6 = new javax.swing.JButton();
        jButtonJ7 = new javax.swing.JButton();
        jButtonJ8 = new javax.swing.JButton();
        jButtonJ9 = new javax.swing.JButton();
        jButtonJ10 = new javax.swing.JButton();
        jButtonJ11 = new javax.swing.JButton();
        jButtonJ12 = new javax.swing.JButton();
        jButtonJ13 = new javax.swing.JButton();
        jButtonJ14 = new javax.swing.JButton();
        jButtonJ15 = new javax.swing.JButton();
        jButtonJ16 = new javax.swing.JButton();
        jLabelFondo2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 30, 20));
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jButtonExit.setBackground(new java.awt.Color(102, 0, 102));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 40));

        jButtonBack.setBackground(new java.awt.Color(102, 0, 102));
        jButtonBack.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));
        jPanel1.add(jLabelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 90, 90));
        jPanel1.add(jLabelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 90, 90));
        jPanel1.add(jLabelUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 90, 90));
        jPanel1.add(jLabelUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 90, 90));
        jPanel1.add(jLabelUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 90, 90));
        jPanel1.add(jLabelUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 90, 90));
        jPanel1.add(jLabelUser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 90, 90));
        jPanel1.add(jLabelUser8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 90, 90));
        jPanel1.add(jLabelUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, 90));
        jPanel1.add(jLabelUser10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 90, 90));
        jPanel1.add(jLabelUser11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 90, 90));
        jPanel1.add(jLabelUser12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 90, 90));
        jPanel1.add(jLabelUser13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 90, 90));
        jPanel1.add(jLabelUser14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 90, 90));
        jPanel1.add(jLabelUser15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 90, 90));
        jPanel1.add(jLabelUser16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 90, 90));

        jButtonJ1.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ1.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 110, 110));

        jButtonJ2.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ2.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, 110));

        jButtonJ3.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ3.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 110, 110));

        jButtonJ4.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ4.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 110, 110));

        jButtonJ5.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ5.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 110, 110));

        jButtonJ6.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ6.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, 110));

        jButtonJ7.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ7.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 110, 110));

        jButtonJ8.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ8.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, 110));

        jButtonJ9.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ9.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 110, 110));

        jButtonJ10.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ10.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ10.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 110, 110));

        jButtonJ11.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ11.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ11.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 110, 110));

        jButtonJ12.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ12.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ12.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 110, 110));

        jButtonJ13.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ13.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ13.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 110, 110));

        jButtonJ14.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ14.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ14.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 110, 110));

        jButtonJ15.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ15.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ15.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 110));

        jButtonJ16.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ16.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ16.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 110));
        jPanel1.add(jLabelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 520));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ4ActionPerformed
    }//GEN-LAST:event_jButtonJ4ActionPerformed

    private void jButtonJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ2ActionPerformed
    }//GEN-LAST:event_jButtonJ2ActionPerformed

    private void jButtonJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ1ActionPerformed
    }//GEN-LAST:event_jButtonJ1ActionPerformed

    private void jButtonJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ5ActionPerformed
    }//GEN-LAST:event_jButtonJ5ActionPerformed

    private void jButtonJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ7ActionPerformed
    }//GEN-LAST:event_jButtonJ7ActionPerformed

    private void jButtonJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ8ActionPerformed
    }//GEN-LAST:event_jButtonJ8ActionPerformed

    private void jButtonJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ3ActionPerformed
    }//GEN-LAST:event_jButtonJ3ActionPerformed

    private void jButtonJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ6ActionPerformed
    }//GEN-LAST:event_jButtonJ6ActionPerformed

    private void jButtonJ16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ16ActionPerformed
    }//GEN-LAST:event_jButtonJ16ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonJ9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ9ActionPerformed

    private void jButtonJ10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ10ActionPerformed

    private void jButtonJ11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ11ActionPerformed

    private void jButtonJ12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ12ActionPerformed

    private void jButtonJ13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ13ActionPerformed

    private void jButtonJ14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ14ActionPerformed

    private void jButtonJ15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJ15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarIconPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarIconPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarIconPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarIconPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarIconPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBack;
    public javax.swing.JButton jButtonExit;
    public javax.swing.JButton jButtonJ1;
    public javax.swing.JButton jButtonJ10;
    public javax.swing.JButton jButtonJ11;
    public javax.swing.JButton jButtonJ12;
    public javax.swing.JButton jButtonJ13;
    public javax.swing.JButton jButtonJ14;
    public javax.swing.JButton jButtonJ15;
    public javax.swing.JButton jButtonJ16;
    public javax.swing.JButton jButtonJ2;
    public javax.swing.JButton jButtonJ3;
    public javax.swing.JButton jButtonJ4;
    public javax.swing.JButton jButtonJ5;
    public javax.swing.JButton jButtonJ6;
    public javax.swing.JButton jButtonJ7;
    public javax.swing.JButton jButtonJ8;
    public javax.swing.JButton jButtonJ9;
    public javax.swing.JLabel jLabelBack;
    public javax.swing.JLabel jLabelExit;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelFondo2;
    public javax.swing.JLabel jLabelUser1;
    public javax.swing.JLabel jLabelUser10;
    public javax.swing.JLabel jLabelUser11;
    public javax.swing.JLabel jLabelUser12;
    public javax.swing.JLabel jLabelUser13;
    public javax.swing.JLabel jLabelUser14;
    public javax.swing.JLabel jLabelUser15;
    public javax.swing.JLabel jLabelUser16;
    public javax.swing.JLabel jLabelUser2;
    public javax.swing.JLabel jLabelUser3;
    public javax.swing.JLabel jLabelUser4;
    public javax.swing.JLabel jLabelUser5;
    public javax.swing.JLabel jLabelUser6;
    public javax.swing.JLabel jLabelUser7;
    public javax.swing.JLabel jLabelUser8;
    public javax.swing.JLabel jLabelUser9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
