/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author Maria
 */
public class ABMTematicas extends javax.swing.JFrame {   
    /**
     * Creates new form gameplay
     */
    public ABMTematicas() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/codigo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconAdmin, "src/imagenes/admin.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconEdit, "src/imagenes/lapiz.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconDelete, "src/imagenes/basura.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoTematica, "src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "src/imagenes/exit.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelBack, "src/imagenes/back.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldTematicas = new javax.swing.JTextField();
        jTextFieldTematica = new javax.swing.JTextField();
        jComboBoxTematica = new javax.swing.JComboBox<>();
        jTextFieldEditarTematica = new javax.swing.JTextField();
        jLabelIconEdit = new javax.swing.JLabel();
        jLabelIconDelete = new javax.swing.JLabel();
        jButtonEliminarTematica = new javax.swing.JButton();
        jButtonEditarTematica = new javax.swing.JButton();
        jLabelFondoTematica = new javax.swing.JLabel();
        jButtonAgregarTematica = new javax.swing.JButton();
        jLabelBack = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelExit = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelIconAdmin = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldTematicas.setEditable(false);
        jTextFieldTematicas.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTematicas.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jTextFieldTematicas.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTematicas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTematicas.setText("TEMATICAS");
        jPanel1.add(jTextFieldTematicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 310, 70));

        jTextFieldTematica.setEditable(false);
        jTextFieldTematica.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTematica.setText("Tematica");
        jPanel1.add(jTextFieldTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 100, 60));

        jComboBoxTematica.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxTematica.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arte", "Biologia", "Ciencia", "Deporte", "Entretenimiento", "Geografia", "Musica", "Historia" }));
        jPanel1.add(jComboBoxTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 160, 60));

        jTextFieldEditarTematica.setBackground(new java.awt.Color(0, 102, 0));
        jTextFieldEditarTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldEditarTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEditarTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFieldEditarTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 270, 40));
        jPanel1.add(jLabelIconEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 60, 50));
        jPanel1.add(jLabelIconDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 60, 50));

        jButtonEliminarTematica.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEliminarTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonEliminarTematica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTematicaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 80, 70));

        jButtonEditarTematica.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEditarTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonEditarTematica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarTematicaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditarTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 80, 70));
        jPanel1.add(jLabelFondoTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 290, 130));

        jButtonAgregarTematica.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAgregarTematica.setFont(new java.awt.Font("Roboto Medium", 0, 70)); // NOI18N
        jButtonAgregarTematica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarTematica.setText("+");
        jButtonAgregarTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTematicaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 80, 70));
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 30));

        jButtonBack.setBackground(new java.awt.Color(0, 102, 0));
        jButtonBack.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 40, 30));

        jButtonExit.setBackground(new java.awt.Color(0, 102, 0));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 60, 50));
        jPanel1.add(jLabelIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 110, 100));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarTematicaActionPerformed

    private void jButtonEditarTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarTematicaActionPerformed

    private void jButtonAgregarTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarTematicaActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMTematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMTematicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAgregarTematica;
    public javax.swing.JButton jButtonBack;
    public javax.swing.JButton jButtonEditarTematica;
    public javax.swing.JButton jButtonEliminarTematica;
    public javax.swing.JButton jButtonExit;
    public javax.swing.JComboBox<String> jComboBoxTematica;
    public javax.swing.JLabel jLabelBack;
    public javax.swing.JLabel jLabelExit;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelFondoTematica;
    public javax.swing.JLabel jLabelIconAdmin;
    public javax.swing.JLabel jLabelIconDelete;
    public javax.swing.JLabel jLabelIconEdit;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldEditarTematica;
    public javax.swing.JTextField jTextFieldTematica;
    public javax.swing.JTextField jTextFieldTematicas;
    // End of variables declaration//GEN-END:variables
}

