/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Maria
 */
public class gameplay extends javax.swing.JFrame {

    /**
     * Creates new form gameplay
     */
    public gameplay() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/azul.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelTematica, "src/imagenes/futbol.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconPts, "src/imagenes/guido.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "src/imagenes/exit.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelConfig, "src/imagenes/config.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelConfig = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonConfig = new javax.swing.JButton();
        jTextFieldPregunta = new javax.swing.JTextField();
        jButtonRtaA = new javax.swing.JButton();
        jButtonRtaB = new javax.swing.JButton();
        jButtonRtaC = new javax.swing.JButton();
        jButtonRtaD = new javax.swing.JButton();
        jLabelRtaA = new javax.swing.JLabel();
        jLabelRtaB = new javax.swing.JLabel();
        jLabelRtaC = new javax.swing.JLabel();
        jLabelRtaD = new javax.swing.JLabel();
        jLabelPuntaje = new javax.swing.JLabel();
        jProgressBarTiempo = new javax.swing.JProgressBar();
        jLabelEscalonRonda = new javax.swing.JLabel();
        jLabelIconPts = new javax.swing.JLabel();
        jLabelTematica = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 30));
        jPanel1.add(jLabelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 40, 30));

        jButtonExit.setBackground(new java.awt.Color(0, 0, 102));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jButtonConfig.setBackground(new java.awt.Color(0, 0, 102));
        jButtonConfig.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonConfig.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jButtonConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 60, 50));

        jTextFieldPregunta.setEditable(false);
        jTextFieldPregunta.setBackground(new java.awt.Color(0, 0, 102));
        jTextFieldPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPregunta.setText("Pregunta");
        jTextFieldPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 580, 70));

        jButtonRtaA.setBackground(new java.awt.Color(0, 0, 102));
        jButtonRtaA.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonRtaA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaA.setText("Respuesta");
        jPanel1.add(jButtonRtaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 240, 40));

        jButtonRtaB.setBackground(new java.awt.Color(0, 0, 102));
        jButtonRtaB.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonRtaB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaB.setText("Respuesta");
        jPanel1.add(jButtonRtaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 240, 40));

        jButtonRtaC.setBackground(new java.awt.Color(0, 0, 102));
        jButtonRtaC.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonRtaC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaC.setText("Respuesta");
        jPanel1.add(jButtonRtaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 240, 40));

        jButtonRtaD.setBackground(new java.awt.Color(0, 0, 102));
        jButtonRtaD.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonRtaD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRtaD.setText("Respuesta");
        jButtonRtaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRtaDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRtaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 240, 40));

        jLabelRtaA.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaA.setText("A.");
        jPanel1.add(jLabelRtaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 30, 40));

        jLabelRtaB.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaB.setText("B.");
        jPanel1.add(jLabelRtaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 30, 40));

        jLabelRtaC.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaC.setText("C.");
        jPanel1.add(jLabelRtaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 30, 40));

        jLabelRtaD.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelRtaD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRtaD.setText("D.");
        jPanel1.add(jLabelRtaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 30, 40));

        jLabelPuntaje.setFont(new java.awt.Font("Roboto Medium", 3, 20)); // NOI18N
        jLabelPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPuntaje.setText("0");
        jPanel1.add(jLabelPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, 50));

        jProgressBarTiempo.setMaximum(30);
        jProgressBarTiempo.setValue(30);
        jPanel1.add(jProgressBarTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 580, 20));

        jLabelEscalonRonda.setFont(new java.awt.Font("Roboto Medium", 3, 20)); // NOI18N
        jLabelEscalonRonda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEscalonRonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEscalonRonda.setText("ESCALON 1 - RONDA 1/2");
        jPanel1.add(jLabelEscalonRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 240, -1));
        jPanel1.add(jLabelIconPts, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 60, 50));
        jPanel1.add(jLabelTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 580, 300));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreguntaActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonRtaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRtaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRtaDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRtaA;
    private javax.swing.JButton jButtonRtaB;
    private javax.swing.JButton jButtonRtaC;
    private javax.swing.JButton jButtonRtaD;
    private javax.swing.JLabel jLabelConfig;
    private javax.swing.JLabel jLabelEscalonRonda;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIconPts;
    private javax.swing.JLabel jLabelPuntaje;
    private javax.swing.JLabel jLabelRtaA;
    private javax.swing.JLabel jLabelRtaB;
    private javax.swing.JLabel jLabelRtaC;
    private javax.swing.JLabel jLabelRtaD;
    private javax.swing.JLabel jLabelTematica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBarTiempo;
    private javax.swing.JTextField jTextFieldPregunta;
    // End of variables declaration//GEN-END:variables
}
