/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Maria
 */
public class Perfiles extends javax.swing.JFrame {

    /**
     * Creates new form gameplay
     */
    public Perfiles() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/MenuPrincipal3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo2, "src/imagenes/violeta.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "src/imagenes/exit.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelBack, "src/imagenes/back.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelConfig, "src/imagenes/config.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser1, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser2, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser3, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser4, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser5, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser6, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser7, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser8, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser9, "src/imagenes/user.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelConfig = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonConfig = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelUser1 = new javax.swing.JLabel();
        jLabelUser2 = new javax.swing.JLabel();
        jLabelUser3 = new javax.swing.JLabel();
        jLabelUser4 = new javax.swing.JLabel();
        jLabelUser5 = new javax.swing.JLabel();
        jLabelUser6 = new javax.swing.JLabel();
        jLabelUser7 = new javax.swing.JLabel();
        jLabelUser8 = new javax.swing.JLabel();
        jLabelUser9 = new javax.swing.JLabel();
        jButtonJ1 = new javax.swing.JButton();
        jButtonJ2 = new javax.swing.JButton();
        jButtonJ3 = new javax.swing.JButton();
        jButtonJ4 = new javax.swing.JButton();
        jButtonJ5 = new javax.swing.JButton();
        jButtonJ6 = new javax.swing.JButton();
        jButtonJ7 = new javax.swing.JButton();
        jButtonJ8 = new javax.swing.JButton();
        jButtonJUser9 = new javax.swing.JButton();
        jTextFieldJ1 = new javax.swing.JTextField();
        jTextFieldJ2 = new javax.swing.JTextField();
        jTextFieldJ3 = new javax.swing.JTextField();
        jTextFieldJ4 = new javax.swing.JTextField();
        jTextFieldJ5 = new javax.swing.JTextField();
        jTextFieldJ6 = new javax.swing.JTextField();
        jTextFieldJ7 = new javax.swing.JTextField();
        jTextFieldJ8 = new javax.swing.JTextField();
        jTextFieldJ9 = new javax.swing.JTextField();
        jTextFieldSeleccionarPerfil = new javax.swing.JTextField();
        jLabelFondo2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 30, 20));
        jPanel1.add(jLabelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 30, 20));
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));

        jButtonExit.setBackground(new java.awt.Color(102, 0, 102));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 40));

        jButtonConfig.setBackground(new java.awt.Color(102, 0, 102));
        jButtonConfig.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonConfig.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 40));

        jButtonBack.setBackground(new java.awt.Color(102, 0, 102));
        jButtonBack.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));
        jPanel1.add(jLabelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 100));
        jPanel1.add(jLabelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 100, 100));
        jPanel1.add(jLabelUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 100, 100));
        jPanel1.add(jLabelUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 100, 100));
        jPanel1.add(jLabelUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 100, 100));
        jPanel1.add(jLabelUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, 100));
        jPanel1.add(jLabelUser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 100, 100));
        jPanel1.add(jLabelUser8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 100, 100));
        jPanel1.add(jLabelUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 100, 100));

        jButtonJ1.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ1.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 120, 120));

        jButtonJ2.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ2.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 120, 120));

        jButtonJ3.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ3.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 120, 120));

        jButtonJ4.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ4.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 120, 120));

        jButtonJ5.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ5.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 120));

        jButtonJ6.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ6.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, 120));

        jButtonJ7.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ7.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 120, 120));

        jButtonJ8.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJ8.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 120, 120));

        jButtonJUser9.setBackground(new java.awt.Color(102, 0, 102));
        jButtonJUser9.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJUser9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJUser9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJUser9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 120, 120));

        jTextFieldJ1.setEditable(false);
        jTextFieldJ1.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ1.setText("Jugador 1");
        jPanel1.add(jTextFieldJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 30));

        jTextFieldJ2.setEditable(false);
        jTextFieldJ2.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ2.setText("Jugador 2");
        jTextFieldJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJ2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 120, 30));

        jTextFieldJ3.setEditable(false);
        jTextFieldJ3.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ3.setText("Jugador 3");
        jTextFieldJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJ3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 120, 30));

        jTextFieldJ4.setEditable(false);
        jTextFieldJ4.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ4.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ4.setText("Jugador 4");
        jPanel1.add(jTextFieldJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 120, 30));

        jTextFieldJ5.setEditable(false);
        jTextFieldJ5.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ5.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ5.setText("Jugador 5");
        jPanel1.add(jTextFieldJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 120, 30));

        jTextFieldJ6.setEditable(false);
        jTextFieldJ6.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ6.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ6.setText("Jugador 6");
        jPanel1.add(jTextFieldJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 120, 30));

        jTextFieldJ7.setEditable(false);
        jTextFieldJ7.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ7.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ7.setText("Jugador 7");
        jPanel1.add(jTextFieldJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 120, 30));

        jTextFieldJ8.setEditable(false);
        jTextFieldJ8.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ8.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ8.setText("Jugador 8");
        jPanel1.add(jTextFieldJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 120, 30));

        jTextFieldJ9.setEditable(false);
        jTextFieldJ9.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ9.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJ9.setText("Jugador 9");
        jPanel1.add(jTextFieldJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 120, 30));

        jTextFieldSeleccionarPerfil.setEditable(false);
        jTextFieldSeleccionarPerfil.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldSeleccionarPerfil.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldSeleccionarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSeleccionarPerfil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSeleccionarPerfil.setText("SELECCIONAR JUGADORES");
        jTextFieldSeleccionarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeleccionarPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSeleccionarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 270, 40));
        jPanel1.add(jLabelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 520));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ4ActionPerformed
    }//GEN-LAST:event_jButtonJ4ActionPerformed

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfigActionPerformed

    private void jButtonJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ2ActionPerformed
    }//GEN-LAST:event_jButtonJ2ActionPerformed

    private void jButtonJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ1ActionPerformed
    }//GEN-LAST:event_jButtonJ1ActionPerformed

    private void jButtonJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ5ActionPerformed
    }//GEN-LAST:event_jButtonJ5ActionPerformed

    private void jButtonJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ7ActionPerformed
    }//GEN-LAST:event_jButtonJ7ActionPerformed

    private void jButtonJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ8ActionPerformed
    }//GEN-LAST:event_jButtonJ8ActionPerformed

    private void jButtonJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ3ActionPerformed
    }//GEN-LAST:event_jButtonJ3ActionPerformed

    private void jButtonJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ6ActionPerformed
    }//GEN-LAST:event_jButtonJ6ActionPerformed

    private void jButtonJUser9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJUser9ActionPerformed
    }//GEN-LAST:event_jButtonJUser9ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldSeleccionarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeleccionarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSeleccionarPerfilActionPerformed

    private void jTextFieldJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJ2ActionPerformed

    private void jTextFieldJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJ3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonJ1;
    private javax.swing.JButton jButtonJ2;
    private javax.swing.JButton jButtonJ3;
    private javax.swing.JButton jButtonJ4;
    private javax.swing.JButton jButtonJ5;
    private javax.swing.JButton jButtonJ6;
    private javax.swing.JButton jButtonJ7;
    private javax.swing.JButton jButtonJ8;
    private javax.swing.JButton jButtonJUser9;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelConfig;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondo2;
    private javax.swing.JLabel jLabelUser1;
    private javax.swing.JLabel jLabelUser2;
    private javax.swing.JLabel jLabelUser3;
    private javax.swing.JLabel jLabelUser4;
    private javax.swing.JLabel jLabelUser5;
    private javax.swing.JLabel jLabelUser6;
    private javax.swing.JLabel jLabelUser7;
    private javax.swing.JLabel jLabelUser8;
    private javax.swing.JLabel jLabelUser9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldJ1;
    private javax.swing.JTextField jTextFieldJ2;
    private javax.swing.JTextField jTextFieldJ3;
    private javax.swing.JTextField jTextFieldJ4;
    private javax.swing.JTextField jTextFieldJ5;
    private javax.swing.JTextField jTextFieldJ6;
    private javax.swing.JTextField jTextFieldJ7;
    private javax.swing.JTextField jTextFieldJ8;
    private javax.swing.JTextField jTextFieldJ9;
    private javax.swing.JTextField jTextFieldSeleccionarPerfil;
    // End of variables declaration//GEN-END:variables
}
