/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Maria
 */
public class Perfiles extends javax.swing.JFrame {

    /**
     * Creates new form gameplay
     */
    public Perfiles() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/azul.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelTematica, "src/imagenes/celeste.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelExit, "src/imagenes/exit.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelConfig, "src/imagenes/config.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelEdit, "src/imagenes/lapiz.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelTrash, "src/imagenes/basura.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser1, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser2, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser3, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser4, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser5, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser6, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser7, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser8, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser9, "src/imagenes/user.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelConfig = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonConfig = new javax.swing.JButton();
        jLabelUser1 = new javax.swing.JLabel();
        jLabelUser2 = new javax.swing.JLabel();
        jLabelUser3 = new javax.swing.JLabel();
        jLabelUser4 = new javax.swing.JLabel();
        jLabelUser5 = new javax.swing.JLabel();
        jLabelUser6 = new javax.swing.JLabel();
        jLabelUser7 = new javax.swing.JLabel();
        jLabelUser8 = new javax.swing.JLabel();
        jLabelUser9 = new javax.swing.JLabel();
        jButtonJ1 = new javax.swing.JButton();
        jButtonJ2 = new javax.swing.JButton();
        jButtonJ3 = new javax.swing.JButton();
        jButtonJ4 = new javax.swing.JButton();
        jButtonJ5 = new javax.swing.JButton();
        jButtonJ6 = new javax.swing.JButton();
        jButtonJ7 = new javax.swing.JButton();
        jButtonJ8 = new javax.swing.JButton();
        jButtonJUser9 = new javax.swing.JButton();
        jLabelAdd = new javax.swing.JLabel();
        jLabelEdit = new javax.swing.JLabel();
        jLabelTrash = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldJ1 = new javax.swing.JTextField();
        jTextFieldJ2 = new javax.swing.JTextField();
        jTextFieldJ3 = new javax.swing.JTextField();
        jTextFieldJ4 = new javax.swing.JTextField();
        jTextFieldJ5 = new javax.swing.JTextField();
        jTextFieldJ6 = new javax.swing.JTextField();
        jTextFieldJ7 = new javax.swing.JTextField();
        jTextFieldJ8 = new javax.swing.JTextField();
        jTextFieldJ9 = new javax.swing.JTextField();
        jLabelEscalon = new javax.swing.JLabel();
        jLabelTematica = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 20));
        jPanel1.add(jLabelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 30, 20));

        jButtonExit.setBackground(new java.awt.Color(0, 0, 153));
        jButtonExit.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jButtonConfig.setBackground(new java.awt.Color(0, 0, 153));
        jButtonConfig.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonConfig.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 40));
        jPanel1.add(jLabelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 70));
        jPanel1.add(jLabelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 70, 70));
        jPanel1.add(jLabelUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 70, 70));
        jPanel1.add(jLabelUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 70, 70));
        jPanel1.add(jLabelUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, 70));
        jPanel1.add(jLabelUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 70, 70));
        jPanel1.add(jLabelUser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 70, 70));
        jPanel1.add(jLabelUser8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 70, 70));
        jPanel1.add(jLabelUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 70, 70));

        jButtonJ1.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ1.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 90));

        jButtonJ2.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ2.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 90, 90));

        jButtonJ3.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ3.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 90, 90));

        jButtonJ4.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ4.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 90, 90));

        jButtonJ5.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ5.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 90));

        jButtonJ6.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ6.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 90));

        jButtonJ7.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ7.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 90, 90));

        jButtonJ8.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJ8.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJ8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 90, 90));

        jButtonJUser9.setBackground(new java.awt.Color(0, 0, 153));
        jButtonJUser9.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonJUser9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJUser9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJUser9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 90, 90));

        jLabelAdd.setFont(new java.awt.Font("Roboto Medium", 0, 60)); // NOI18N
        jLabelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdd.setText("+");
        jPanel1.add(jLabelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 90));
        jPanel1.add(jLabelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 40, 30));
        jPanel1.add(jLabelTrash, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 40, 30));

        jButtonEdit.setBackground(new java.awt.Color(0, 0, 153));
        jButtonEdit.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 60, 50));

        jButtonRemove.setBackground(new java.awt.Color(0, 0, 153));
        jButtonRemove.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonRemove.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 60, 50));

        jButtonAdd.setBackground(new java.awt.Color(0, 0, 153));
        jButtonAdd.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 90));

        jTextFieldJ1.setEditable(false);
        jTextFieldJ1.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ1.setText("Jugador 1");
        jPanel1.add(jTextFieldJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jTextFieldJ2.setEditable(false);
        jTextFieldJ2.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ2.setText("Jugador 2");
        jPanel1.add(jTextFieldJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jTextFieldJ3.setEditable(false);
        jTextFieldJ3.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ3.setText("Jugador 3");
        jPanel1.add(jTextFieldJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jTextFieldJ4.setEditable(false);
        jTextFieldJ4.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ4.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ4.setText("Jugador 4");
        jPanel1.add(jTextFieldJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jTextFieldJ5.setEditable(false);
        jTextFieldJ5.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ5.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ5.setText("Jugador 5");
        jPanel1.add(jTextFieldJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jTextFieldJ6.setEditable(false);
        jTextFieldJ6.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ6.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ6.setText("Jugador 6");
        jPanel1.add(jTextFieldJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jTextFieldJ7.setEditable(false);
        jTextFieldJ7.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ7.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ7.setText("Jugador 7");
        jPanel1.add(jTextFieldJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jTextFieldJ8.setEditable(false);
        jTextFieldJ8.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ8.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ8.setText("Jugador 8");
        jPanel1.add(jTextFieldJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jTextFieldJ9.setEditable(false);
        jTextFieldJ9.setBackground(new java.awt.Color(0, 0, 153));
        jTextFieldJ9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ9.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ9.setText("Jugador 9");
        jPanel1.add(jTextFieldJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabelEscalon.setFont(new java.awt.Font("Roboto Medium", 3, 30)); // NOI18N
        jLabelEscalon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEscalon.setText("SELECCIONAR PERFIL");
        jPanel1.add(jLabelEscalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 330, 60));
        jPanel1.add(jLabelTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 580, 480));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -390, 660, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ4ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ4ActionPerformed

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfigActionPerformed

    private void jButtonJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ2ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ2ActionPerformed

    private void jButtonJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ1ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ1ActionPerformed

    private void jButtonJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ5ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ5ActionPerformed

    private void jButtonJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ7ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ7ActionPerformed

    private void jButtonJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ8ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ8ActionPerformed

    private void jButtonJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ3ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ3ActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ6ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJ6ActionPerformed

    private void jButtonJUser9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJUser9ActionPerformed
        Gameplay newFrame = new Gameplay();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJUser9ActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonJ1;
    private javax.swing.JButton jButtonJ2;
    private javax.swing.JButton jButtonJ3;
    private javax.swing.JButton jButtonJ4;
    private javax.swing.JButton jButtonJ5;
    private javax.swing.JButton jButtonJ6;
    private javax.swing.JButton jButtonJ7;
    private javax.swing.JButton jButtonJ8;
    private javax.swing.JButton jButtonJUser9;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelConfig;
    private javax.swing.JLabel jLabelEdit;
    private javax.swing.JLabel jLabelEscalon;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTematica;
    private javax.swing.JLabel jLabelTrash;
    private javax.swing.JLabel jLabelUser1;
    private javax.swing.JLabel jLabelUser2;
    private javax.swing.JLabel jLabelUser3;
    private javax.swing.JLabel jLabelUser4;
    private javax.swing.JLabel jLabelUser5;
    private javax.swing.JLabel jLabelUser6;
    private javax.swing.JLabel jLabelUser7;
    private javax.swing.JLabel jLabelUser8;
    private javax.swing.JLabel jLabelUser9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldJ1;
    private javax.swing.JTextField jTextFieldJ2;
    private javax.swing.JTextField jTextFieldJ3;
    private javax.swing.JTextField jTextFieldJ4;
    private javax.swing.JTextField jTextFieldJ5;
    private javax.swing.JTextField jTextFieldJ6;
    private javax.swing.JTextField jTextFieldJ7;
    private javax.swing.JTextField jTextFieldJ8;
    private javax.swing.JTextField jTextFieldJ9;
    // End of variables declaration//GEN-END:variables
}
