//EJEMPLO LOGISTICA Y TRANSPORTE 
public class App {
    public static void main(String[] args) throws Exception {
        Creador creadorA = new CreadorConcretoA(); ///CREO UN CREADOR CONCRETO(A), DE TIPO CREADOR
        creadorA.planificarEntrega(); //REALIZA UN METODO DEFINIDO EN CREADOR CONCRETO(A)
        
        //USAR CUANDO:
        //UNA CLASE NO PUEDE ANTICIPIAR QUE CLASE DE OBJETOS DEBE SER CREADA
        //UNA CLASE QUIERE QUE SU SUBLCLASE ESPECIFIQUE EL OBJETO A CREAR
        
        //LAS CLASES DELEGAN LA RESPONSABILIDAD A UNA DE SUS MUCHAS SUBLCASES, Y ES NECESARIO UBICAR CUÁL DE TODAS
        //ESAS SUBLCASES ES LA QUE PUEDE DAR REPSUESTA A LA NECESIDAD ACTUAL
    }
}
