/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author Maria
 */
public class ABMPreguntas extends javax.swing.JFrame {   
    /**
     * Creates new form gameplay
     */
    public ABMPreguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/codigo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconAdmin, "src/imagenes/admin.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconEdit, "src/imagenes/lapiz.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelIconDelete, "src/imagenes/basura.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoTematica, "src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoTipo, "src/imagenes/verde.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondoPregunta, "src/imagenes/verde.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIconAdmin = new javax.swing.JLabel();
        jTextFieldABMPreguntas = new javax.swing.JTextField();
        jTextFieldTematica = new javax.swing.JTextField();
        jComboBoxTematica = new javax.swing.JComboBox<>();
        jTextFieldNuevaTematica = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldNuevoTipo = new javax.swing.JTextField();
        jTextFieldPregunta = new javax.swing.JTextField();
        jComboBoxPregunta = new javax.swing.JComboBox<>();
        jTextFieldNuevaPregunta = new javax.swing.JTextField();
        jButtonGuardarSalir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelIconEdit = new javax.swing.JLabel();
        jLabelIconDelete = new javax.swing.JLabel();
        jButtonEliminarPregunta = new javax.swing.JButton();
        jButtonModificarPregunta = new javax.swing.JButton();
        jButtonAñadirTematica = new javax.swing.JButton();
        jButtonAñadirPregunta = new javax.swing.JButton();
        jButtonAñadirTipo = new javax.swing.JButton();
        jLabelFondoTematica = new javax.swing.JLabel();
        jLabelFondoTipo = new javax.swing.JLabel();
        jLabelFondoPregunta = new javax.swing.JLabel();
        jButtonAgregarPregunta = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 60, 50));

        jTextFieldABMPreguntas.setEditable(false);
        jTextFieldABMPreguntas.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldABMPreguntas.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jTextFieldABMPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldABMPreguntas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldABMPreguntas.setText("PREGUNTAS");
        jPanel1.add(jTextFieldABMPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 310, 70));

        jTextFieldTematica.setEditable(false);
        jTextFieldTematica.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTematica.setText("Tematica");
        jPanel1.add(jTextFieldTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 60));

        jComboBoxTematica.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxTematica.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arte", "Biologia", "Ciencia", "Deporte", "Entretenimiento", "Geografia", "Musica", "Historia" }));
        jPanel1.add(jComboBoxTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, 60));

        jTextFieldNuevaTematica.setBackground(new java.awt.Color(0, 102, 0));
        jTextFieldNuevaTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldNuevaTematica.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNuevaTematica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFieldNuevaTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 270, 40));

        jTextFieldTipo.setEditable(false);
        jTextFieldTipo.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldTipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTipo.setText("Tipo");
        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 100, 60));

        jComboBoxTipo.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multiple choice", "Aproximacion"}));
        jPanel1.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 160, 60));

        jTextFieldNuevoTipo.setBackground(new java.awt.Color(0, 102, 0));
        jTextFieldNuevoTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldNuevoTipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNuevoTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFieldNuevoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 270, 40));

        jTextFieldPregunta.setEditable(false);
        jTextFieldPregunta.setBackground(new java.awt.Color(51, 153, 0));
        jTextFieldPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPregunta.setText("Pregunta");
        jPanel1.add(jTextFieldPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 570, 50));

        jComboBoxPregunta.setBackground(new java.awt.Color(51, 153, 0));
        jComboBoxPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jComboBoxPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 570, 50));

        jTextFieldNuevaPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jTextFieldNuevaPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jTextFieldNuevaPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNuevaPregunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFieldNuevaPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 570, 50));

        jButtonGuardarSalir.setBackground(new java.awt.Color(0, 102, 0));
        jButtonGuardarSalir.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonGuardarSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarSalir.setText("GUARDAR Y SALIR");
        jButtonGuardarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardarSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 30));

        jButtonSalir.setBackground(new java.awt.Color(0, 102, 0));
        jButtonSalir.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR SIN GUARDAR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 220, 30));
        jPanel1.add(jLabelIconEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 60, 50));
        jPanel1.add(jLabelIconDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 60, 50));

        jButtonEliminarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEliminarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonEliminarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 80, 70));

        jButtonModificarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonModificarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonModificarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 80, 70));

        jButtonAñadirTematica.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAñadirTematica.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonAñadirTematica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAñadirTematica.setText("Añadir Tematica");
        jButtonAñadirTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirTematicaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAñadirTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 270, 40));

        jButtonAñadirPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAñadirPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonAñadirPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAñadirPregunta.setText("Añadir Pregunta");
        jButtonAñadirPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAñadirPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 570, 50));

        jButtonAñadirTipo.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAñadirTipo.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jButtonAñadirTipo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAñadirTipo.setText("Añadir Tipo");
        jButtonAñadirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAñadirTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 270, 40));
        jPanel1.add(jLabelFondoTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 180));
        jPanel1.add(jLabelFondoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 290, 180));
        jPanel1.add(jLabelFondoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 590, 250));

        jButtonAgregarPregunta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAgregarPregunta.setFont(new java.awt.Font("Roboto Medium", 0, 70)); // NOI18N
        jButtonAgregarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarPregunta.setText("+");
        jButtonAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 80, 70));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGuardarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarSalirActionPerformed

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonEliminarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarPreguntaActionPerformed

    private void jButtonModificarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarPreguntaActionPerformed

    private void jButtonAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPreguntaActionPerformed

    private void jComboBoxPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPreguntaActionPerformed

    private void jButtonAñadirTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirTematicaActionPerformed

    private void jButtonAñadirPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirPreguntaActionPerformed

    private void jButtonAñadirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarPregunta;
    private javax.swing.JButton jButtonAñadirPregunta;
    private javax.swing.JButton jButtonAñadirTematica;
    private javax.swing.JButton jButtonAñadirTipo;
    private javax.swing.JButton jButtonEliminarPregunta;
    private javax.swing.JButton jButtonGuardarSalir;
    private javax.swing.JButton jButtonModificarPregunta;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxPregunta;
    private javax.swing.JComboBox<String> jComboBoxTematica;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoPregunta;
    private javax.swing.JLabel jLabelFondoTematica;
    private javax.swing.JLabel jLabelFondoTipo;
    private javax.swing.JLabel jLabelIconAdmin;
    private javax.swing.JLabel jLabelIconDelete;
    private javax.swing.JLabel jLabelIconEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldABMPreguntas;
    private javax.swing.JTextField jTextFieldNuevaPregunta;
    private javax.swing.JTextField jTextFieldNuevaTematica;
    private javax.swing.JTextField jTextFieldNuevoTipo;
    private javax.swing.JTextField jTextFieldPregunta;
    private javax.swing.JTextField jTextFieldTematica;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}

