/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Maria
 */
public class SiguienteEscalon extends javax.swing.JFrame {
        private Timer timer; 
        private int tiempo;
    /**
     * Creates new form gameplay
     */
    public SiguienteEscalon() {
        initComponents();
        iniciarCronometro();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo, "src/imagenes/MenuPrincipal3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelFondo2, "src/imagenes/violeta.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser1, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser2, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser3, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser4, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser5, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser6, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser7, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser8, "src/imagenes/user.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabelUser9, "src/imagenes/user.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLevelUp = new javax.swing.JLabel();
        jProgressBarTiempo = new javax.swing.JProgressBar();
        jLabelUser1 = new javax.swing.JLabel();
        jLabelUser2 = new javax.swing.JLabel();
        jLabelUser3 = new javax.swing.JLabel();
        jLabelUser4 = new javax.swing.JLabel();
        jLabelUser5 = new javax.swing.JLabel();
        jLabelUser6 = new javax.swing.JLabel();
        jLabelUser7 = new javax.swing.JLabel();
        jLabelUser8 = new javax.swing.JLabel();
        jLabelUser9 = new javax.swing.JLabel();
        jTextFieldJ1 = new javax.swing.JTextField();
        jTextFieldJ2 = new javax.swing.JTextField();
        jTextFieldJ3 = new javax.swing.JTextField();
        jTextFieldJ4 = new javax.swing.JTextField();
        jTextFieldJ5 = new javax.swing.JTextField();
        jTextFieldJ6 = new javax.swing.JTextField();
        jTextFieldJ7 = new javax.swing.JTextField();
        jTextFieldJ8 = new javax.swing.JTextField();
        jTextFieldJ9 = new javax.swing.JTextField();
        jLabelJ1 = new javax.swing.JLabel();
        jLabelJ2 = new javax.swing.JLabel();
        jLabelJ3 = new javax.swing.JLabel();
        jLabelJ4 = new javax.swing.JLabel();
        jLabelJ5 = new javax.swing.JLabel();
        jLabelJ6 = new javax.swing.JLabel();
        jLabelJ7 = new javax.swing.JLabel();
        jLabelJ8 = new javax.swing.JLabel();
        jLabelJ9 = new javax.swing.JLabel();
        jLabelFondo2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLevelUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/level-up.gif"))); // NOI18N
        jPanel1.add(jLabelLevelUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, 90));

        jProgressBarTiempo.setForeground(new java.awt.Color(0, 0, 153));
        jProgressBarTiempo.setMaximum(5);
        jPanel1.add(jProgressBarTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 20));
        jPanel1.add(jLabelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 70, 70));
        jPanel1.add(jLabelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, 70));
        jPanel1.add(jLabelUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, 70));
        jPanel1.add(jLabelUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 70, 70));
        jPanel1.add(jLabelUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 70, 70));
        jPanel1.add(jLabelUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 70, 70));
        jPanel1.add(jLabelUser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 70, 70));
        jPanel1.add(jLabelUser8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 70, 70));
        jPanel1.add(jLabelUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 70, 70));

        jTextFieldJ1.setEditable(false);
        jTextFieldJ1.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ1.setText("Jugador 1");
        jPanel1.add(jTextFieldJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jTextFieldJ2.setEditable(false);
        jTextFieldJ2.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ2.setText("Jugador 2");
        jPanel1.add(jTextFieldJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jTextFieldJ3.setEditable(false);
        jTextFieldJ3.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ3.setText("Jugador 3");
        jPanel1.add(jTextFieldJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jTextFieldJ4.setEditable(false);
        jTextFieldJ4.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ4.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ4.setText("Jugador 4");
        jPanel1.add(jTextFieldJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jTextFieldJ5.setEditable(false);
        jTextFieldJ5.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ5.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ5.setText("Jugador 5");
        jTextFieldJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJ5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jTextFieldJ6.setEditable(false);
        jTextFieldJ6.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ6.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ6.setText("Jugador 6");
        jPanel1.add(jTextFieldJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jTextFieldJ7.setEditable(false);
        jTextFieldJ7.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ7.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ7.setText("Jugador 7");
        jPanel1.add(jTextFieldJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jTextFieldJ8.setEditable(false);
        jTextFieldJ8.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ8.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ8.setText("Jugador 8");
        jPanel1.add(jTextFieldJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        jTextFieldJ9.setEditable(false);
        jTextFieldJ9.setBackground(new java.awt.Color(102, 0, 102));
        jTextFieldJ9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTextFieldJ9.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldJ9.setText("Jugador 9");
        jPanel1.add(jTextFieldJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabelJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 90));

        jLabelJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, 90));

        jLabelJ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 90, 90));

        jLabelJ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 90, 90));

        jLabelJ5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 90, 90));

        jLabelJ6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 90, 90));

        jLabelJ7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rojo.png"))); // NOI18N
        jPanel1.add(jLabelJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 90, 90));

        jLabelJ8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 90, 90));

        jLabelJ9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.png"))); // NOI18N
        jPanel1.add(jLabelJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 90, 90));
        jPanel1.add(jLabelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 540, 430));

        jLabelFondo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJ5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiguienteEscalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiguienteEscalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiguienteEscalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiguienteEscalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiguienteEscalon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondo2;
    private javax.swing.JLabel jLabelJ1;
    private javax.swing.JLabel jLabelJ2;
    private javax.swing.JLabel jLabelJ3;
    private javax.swing.JLabel jLabelJ4;
    private javax.swing.JLabel jLabelJ5;
    private javax.swing.JLabel jLabelJ6;
    private javax.swing.JLabel jLabelJ7;
    private javax.swing.JLabel jLabelJ8;
    private javax.swing.JLabel jLabelJ9;
    private javax.swing.JLabel jLabelLevelUp;
    private javax.swing.JLabel jLabelUser1;
    private javax.swing.JLabel jLabelUser2;
    private javax.swing.JLabel jLabelUser3;
    private javax.swing.JLabel jLabelUser4;
    private javax.swing.JLabel jLabelUser5;
    private javax.swing.JLabel jLabelUser6;
    private javax.swing.JLabel jLabelUser7;
    private javax.swing.JLabel jLabelUser8;
    private javax.swing.JLabel jLabelUser9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBarTiempo;
    private javax.swing.JTextField jTextFieldJ1;
    private javax.swing.JTextField jTextFieldJ2;
    private javax.swing.JTextField jTextFieldJ3;
    private javax.swing.JTextField jTextFieldJ4;
    private javax.swing.JTextField jTextFieldJ5;
    private javax.swing.JTextField jTextFieldJ6;
    private javax.swing.JTextField jTextFieldJ7;
    private javax.swing.JTextField jTextFieldJ8;
    private javax.swing.JTextField jTextFieldJ9;
    // End of variables declaration//GEN-END:variables
    private void iniciarCronometro(){
    tiempo=5;
    timer = new Timer(1000, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) { 
            tiempo--;
            jProgressBarTiempo.setValue(tiempo); 
            if (tiempo <= 0) { 
                timer.stop();
            }
        }
    });
    timer.start();
    }
}

